package io.github.yasmramos.veld;

/**
 * Stub class for Veld DI container compile-time compatibility.
 *
 * <p>This stub provides method signatures for compile-time compatibility.
 * During annotation processing, this class is replaced by a generated
 * implementation with static factory methods for all components.</p>
 *
 * <p><b>Note:</b> Do not use this class directly. Use the generated
 * static methods instead.</p>
 */
public final class Veld {

    private Veld() {
        // Private constructor - do not instantiate
    }

    // Static factory methods will be generated by veld-processor
    // These stubs prevent compile errors in user code before processing
}
