# Funding Configuration for Veld Framework

# These settings enable sponsor buttons and links across GitHub
# IMPORTANT: GitHub Sponsors requires enrollment at https://github.com/sponsors
# Uncomment the github line once enrolled, otherwise remove or comment it

# GitHub Sponsors (requires enrollment)
# github: yasmramos

# Custom funding links (e.g., Ko-fi, Buy Me a Coffee)
# custom: ["ko-fi.com/yourusername", "buymeacoffee.com/yourusername"]

# Open Collective (optional)
# open_collective: veld-framework

# Patreon (optional)
# patron: yourusername

# Ko-fi (optional)
# ko_fi: yourusername

# Liberapay (optional)
# liberapay: username

# Bitcoin (optional)
# bitcoin: 1YourBitcoinAddress

# Ethereum (optional)
# ethereum: 0xYourEthereumAddress

---

**Note**: This file enables funding links on your GitHub repository.
To activate GitHub Sponsors, visit https://github.com/sponsors and apply.
For other platforms, create accounts and uncomment the relevant lines.

**Last Updated**: 2025-01-09
**Version**: 1.0.4
