#!/bin/bash
# Script para configurar el GitHub Project automáticamente
# Requiere: jq instalado

# Configura tu token:
# export GITHUB_TOKEN="ghp_tu_token_aquí"

echo "🎯 Configurando GitHub Project para Veld Framework..."
echo ""
echo "📋 Proyecto: https://github.com/users/yasmramos/projects/1"
echo ""
echo "⚠️  NOTA: La API de GitHub Projects v2 requiere configuración manual"
echo "   para columnas y campos de estado."
echo ""
echo "📝 Pasos para configurar manualmente:"
echo ""
echo "1. Abre: https://github.com/users/yasmramos/projects/1"
echo ""
echo "2. Click en 'Add view' (arriba a la derecha)"
echo "   → Selecciona 'Board'"
echo ""
echo "3. Configura el campo 'Status' con estas opciones:"
echo "   ┌─────────────┬──────────────┬─────────┬─────────┬───────┐"
echo "   │   🔲 To Do  │  🔄 In Prog  │ 📍Fase 1│ 📍Fase 2│ ✅DONE│"
echo "   └─────────────┴──────────────┴─────────┴─────────┴───────┘"
echo ""
echo "4. Añade los 25 issues desde: .github/PROJECT_TEMPLATE.md"
echo ""
echo "📊 Resumen del proyecto:"
echo "   - Total issues planificados: 25"
echo "   - Completados (v1.0.3): 12"
echo "   - Fase 1: 11 issues"
echo "   - Fase 2: 5 issues"
echo ""
echo "📁 Documentación:"
echo "   - Roadmap: https://github.com/yasmramos/Veld/blob/develop/ROADMAP.md"
echo "   - Changelog: https://github.com/yasmramos/Veld/blob/develop/CHANGELOG.md"
echo "   - Plantilla: .github/PROJECT_TEMPLATE.md"
echo ""
echo "✅ ¡Proyecto listo para usar!"
