package com.veld.processor;

import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

/**
 * Generates the Veld bootstrap class as bytecode using ASM.
 * This class provides zero-reflection access to the DI container.
 * 
 * Generated class: com.veld.generated.Veld
 * 
 * Usage:
 *   VeldContainer container = Veld.createContainer();
 *   // or
 *   ComponentRegistry registry = Veld.createRegistry();
 */
public class VeldBootstrapGenerator implements Opcodes {
    
    private static final String VELD_CLASS = "com/veld/generated/Veld";
    private static final String REGISTRY_CLASS = "com/veld/generated/VeldRegistry";
    private static final String CONTAINER_CLASS = "com/veld/runtime/VeldContainer";
    private static final String COMPONENT_REGISTRY_CLASS = "com/veld/runtime/ComponentRegistry";
    
    /**
     * Generates the Veld bootstrap class bytecode.
     * 
     * @return the generated bytecode
     */
    public byte[] generate() {
        ClassWriter cw = new ClassWriter(ClassWriter.COMPUTE_FRAMES | ClassWriter.COMPUTE_MAXS);
        
        // public final class Veld
        cw.visit(V11, ACC_PUBLIC | ACC_FINAL, VELD_CLASS, null, "java/lang/Object", null);
        
        // Private constructor to prevent instantiation
        generatePrivateConstructor(cw);
        
        // public static VeldContainer createContainer()
        generateCreateContainer(cw);
        
        // public static ComponentRegistry createRegistry()
        generateCreateRegistry(cw);
        
        cw.visitEnd();
        return cw.toByteArray();
    }
    
    private void generatePrivateConstructor(ClassWriter cw) {
        MethodVisitor mv = cw.visitMethod(ACC_PRIVATE, "<init>", "()V", null, null);
        mv.visitCode();
        mv.visitVarInsn(ALOAD, 0);
        mv.visitMethodInsn(INVOKESPECIAL, "java/lang/Object", "<init>", "()V", false);
        mv.visitInsn(RETURN);
        mv.visitMaxs(0, 0);
        mv.visitEnd();
    }
    
    private void generateCreateContainer(ClassWriter cw) {
        // public static VeldContainer createContainer()
        MethodVisitor mv = cw.visitMethod(
                ACC_PUBLIC | ACC_STATIC,
                "createContainer",
                "()L" + CONTAINER_CLASS + ";",
                null,
                null);
        mv.visitCode();
        
        // return new VeldContainer(createRegistry());
        mv.visitTypeInsn(NEW, CONTAINER_CLASS);
        mv.visitInsn(DUP);
        
        // Call createRegistry() to get the registry
        mv.visitMethodInsn(INVOKESTATIC, VELD_CLASS, "createRegistry", 
                "()L" + COMPONENT_REGISTRY_CLASS + ";", false);
        
        // Call VeldContainer constructor
        mv.visitMethodInsn(INVOKESPECIAL, CONTAINER_CLASS, "<init>", 
                "(L" + COMPONENT_REGISTRY_CLASS + ";)V", false);
        
        mv.visitInsn(ARETURN);
        mv.visitMaxs(0, 0);
        mv.visitEnd();
    }
    
    private void generateCreateRegistry(ClassWriter cw) {
        // public static ComponentRegistry createRegistry()
        MethodVisitor mv = cw.visitMethod(
                ACC_PUBLIC | ACC_STATIC,
                "createRegistry",
                "()L" + COMPONENT_REGISTRY_CLASS + ";",
                null,
                null);
        mv.visitCode();
        
        // return new VeldRegistry();
        mv.visitTypeInsn(NEW, REGISTRY_CLASS);
        mv.visitInsn(DUP);
        mv.visitMethodInsn(INVOKESPECIAL, REGISTRY_CLASS, "<init>", "()V", false);
        mv.visitInsn(ARETURN);
        
        mv.visitMaxs(0, 0);
        mv.visitEnd();
    }
    
    public String getClassName() {
        return VELD_CLASS.replace('/', '.');
    }
}
