/*
 * Copyright 2025 Veld Framework
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.github.yasmramos.veld.aop.proxy;

/**
 * Marker interface for AOP proxy instances.
 *
 * <p>All proxies generated by the AOP framework implement this interface,
 * allowing detection of proxied instances.
 *
 * @author Veld Framework Team
 * @since 1.0.0-alpha.5
 */
public interface AopProxy {

    /**
     * Returns the original (non-proxied) target object.
     *
     * @return the target object
     */
    Object getTargetObject();

    /**
     * Returns the target class (the original class, not the proxy class).
     *
     * @return the target class
     */
    Class<?> getTargetClass();

    /**
     * Checks if a given object is an AOP proxy.
     *
     * @param obj the object to check
     * @return true if the object is an AOP proxy
     */
    static boolean isProxy(Object obj) {
        return obj instanceof AopProxy;
    }

    /**
     * Gets the target object from a potential proxy.
     *
     * @param obj the object (may be a proxy)
     * @return the target object, or the object itself if not a proxy
     */
    static Object unwrap(Object obj) {
        return obj instanceof AopProxy proxy ? proxy.getTargetObject() : obj;
    }
}
